version: "3.3"

networks:
  net:
    driver: bridge

services:
  # database
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-container'
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d example"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net
  # service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 4G
    container_name: 'app-container'
    restart: unless-stopped
    hostname: server
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/example?sslmode=disable # должно быть в секретах/конфиге. Учебный пример
    ports:
      - 8080:8080
      # - 8090:8090
    command: ./app
    depends_on:
      - postgres
    networks:
      - net

